<!DOCTYPE html>
<html>

<head>
<link rel="stylesheet" href="style.css">
<title>Hello World</title>
</head>

<body>


<p class = "black" >
<ul class="black" class="center">
<li class="currentpage" ><h3><a href="index.php">Index</a></h3></li>
<li><h3><a href="Strings.php">String</a></h3></li>
<li><h3><a href="Number3.php">Number3</a></h3></li>
<li><h3><a href="arrays.php">Arrays</a></h3></li>
<li><h3><a href="assarray.php">Associative Arrays</a></h3></li>
<li><h3><a href="connect.php">Connection</a></h3></li
><li><h3><a href="CreateDB.php">Create DB</a></h3></li>
<!-- <li><h3><a href="table.php">Create Table</a></h3></li> -->
 <!-- <li><h3><a href="tabledata.php">Add Table data</a></h3></li> -->
<li><h3><a href="ASSIGNMENT2.php">Form</a></h3></li>
<!-- <li><h3><a href="A2_table.php">A2TABLE</a></h3></li> -->
<li>
    <h3><a href="DisplayTable.php">View Data from database</a></h3></li>
</ul></p>
<h1 class="center" , class="red" >  Server Homepage  </h1>
<?php

echo "Hello, World!";
echo "<br>";
if(2+2 == 4){
    print("Good - i avent totally lost me mind");
    print("Lost my mind.<br>");

}


?>


</body>

</html>
