<!DOCTYPE html><html>

<head>
<link rel="stylesheet" href="style.css">
<title>Hello World</title>
</head>

<body class="yellow">
<h1 class="center" , class="red" >  Server Homepage  </h1>
<?php

echo "Hello, World!";
echo "<br>";
if(2+2 == 4){
    print("Good - i avent totally lost me mind");
    print("Lost my mind.<br>");

}


?>
<h3><a href="Strings.php">String</a></h3>
<h3><a href="Number3.php">Number3</a></h3>
<h3><a href="arrays.php">Arrays</a></h3>
<h3><a href="assarray.php">Associative Arrays</a></h3>
<h3><a href="connect.php">Connection</a></h3>
</body>

</html>
